apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    component: grafana
    app: "mantis"
    zone: "zone"
  annotations:
    jcs.com/algorithm.80: SOURCE_IP
spec:
  sessionAffinity: ClientIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    component: grafana
    app: "mantis"
    zone: "zone"
